services:
  api:
    image: drunkenmaster-api
    restart: always
    environment:
      - MONGODB_CONNECTION_STRING=mongodb://user:pass@mongodb
      - ASPNETCORE_ENVIRONMENT=Docker
    build:
      context: ./DrunkenMaster.Net/
      dockerfile: ./.docker/Dockerfile
    ports:
      - 5001:5001
      - 443:443
      - 80:80
    depends_on:
      - mongodb
    networks:
      main:
        aliases:
          - api
  ui:
    image: drunkenmasternet-ui
    build:
      context: ./DrunkenMaster.Net.UI/
      dockerfile: ./.docker/Dockerfile
    ports:
      - 8080:80
    links:
      - api:api
    depends_on:
      - api
    networks:
      main:
        aliases:
          - ui
  mongodb:
    image: mongodb/mongodb-community-server:6.0.15-ubi9
    restart: always
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=user
      - MONGODB_INITDB_ROOT_PASSWORD=pass
    volumes:
      # seeding scripts
      - ./.docker/mongo-entrypoint:/docker-entrypoint-initdb.d
      # named volumes
      - mongodb:/data/db
      - mongoconfig:/data/configdb
    networks:
       main:
        aliases:
          - mongodb
volumes:
  mongodb:
  mongoconfig:
networks:
  main:
    driver: bridge